-- Usuarios
SELECT * FROM usuarios;

INSERT INTO usuarios(email,password,type,name)
VALUES ('contacto@test.cl','$2b$10$XScTj3gu2BFkg9mwf3w1BOI4V85.S5jSwTXtGIveLGxf50GLbjTo6','superuser','Administrador General');

-- Alarmas

INSERT INTO alarmas (name, type, delay, inhibit, state, "group")
VALUES
('Alta Temperatura Motor Secundario', 'NC', 2000, false, 2, 1),
('Baja Presión de Aceite', 'NO', 1000, false, 3, 1),
('Falla Sensor Voltaje', 'NC', 1500, false, 1, 3),
('Bomba Sentina Fallida', 'NO', 2000, false, 0, 5),
('Nivel Agua Bajo', 'NC', 1500, false, 1, 4),
('Fuga de Combustible Detectada', 'NO', 0, false, 0, 1),
('Humo Detectado', 'NC', 500, false, 0, 6),
('Corriente de Arranque Excesiva', 'NO', 500, false, 0, 1),
('Bajo Nivel de Refrigerante', 'NC', 2500, false, 0, 1),
('Alta Temperatura de Escape', 'NO', 1200, false, 0, 1),
('Baja Tensión General', 'NC', 1000, false, 0, 3),
('Fuego Detectado', 'NO', 1000, false, 0, 6),
('RPM Motor Elevadas', 'NC', 500, false, 0, 1),
('Sobre RPM Permitidas', 'NO', 800, false, 0, 1),
('Bajo Nivel Combustible', 'NC', 2000, false, 0, 4),
('Vibración Excesiva', 'NO', 1500, false, 0, 1),
('Puerta Abierta', 'NC', 0, false, 1, 6),
('Alta Temperatura Caja Reductora', 'NO', 1800, false, 0, 2),
('Voltaje Excesivo', 'NC', 800, false, 0, 3),
('Fallo Batería Principal', 'NO', 2000, false, 0, 3),
('Vibración Caja Crítica', 'NC', 1500, false, 0, 2),
('Nivel Combustible Crítico', 'NO', 1800, false, 0, 4),
('Bajo Nivel Aceite Crítico', 'NC', 1000, false, 0, 4),
('Alta Agua Sentina', 'NO', 1500, false, 0, 5),
('Falla Bomba Sentina Crítica', 'NC', 2000, false, 0, 5),
('Falla Sistema Alarma', 'NO', 0, false, 0, 6),
('Alta Temperatura Motor Crítica', 'NC', 2000, false, 0, 1),
('Baja Presión Aceite Crítica', 'NO', 1000, false, 0, 1),
('Falla Sensor Voltaje Crítica', 'NC', 1500, false, 0, 3),
('Bomba Sentina Fallida Crítica', 'NO', 2000, false, 0, 5),
('Nivel Agua Muy Bajo', 'NC', 1500, false, 0, 4),
('Fuga de Combustible Grave', 'NO', 0, false, 0, 1),
('Humo Denso Detectado', 'NC', 500, false, 0, 6),
('Corriente de Arranque Peligrosa', 'NO', 500, false, 0, 1),
('Bajo Nivel de Refrigerante Crítico', 'NC', 2500, false, 0, 1),
('Alta Temperatura de Escape Crítica', 'NO', 1200, false, 0, 1),
('Baja Tensión General Crítica', 'NC', 1000, false, 0, 3),
('Fuego Extenso Detectado', 'NO', 1000, false, 0, 6),
('Falla de Inyección Motor', 'NC', 1200, false, 0, 1),
('Baja Presión Caja Reductora', 'NC', 1000, false, 0, 2),
('Falla Engranaje Principal', 'NO', 2000, false, 0, 2),
('Corto Circuito Detectado', 'NC', 500, false, 0, 3),
('Fallo Generador Principal', 'NO', 1500, false, 0, 3),
('Nivel de Aceite Bajo', 'NC', 1000, false, 0, 4),
('Nivel de Agua Crítico', 'NO', 2000, false, 0, 4),
('Obstrucción en Bomba Sentina', 'NC', 1800, false, 0, 5),
('Fuga de Agua en Sentina', 'NO', 1500, false, 0, 5),
('Puerta de Emergencia Abierta', 'NC', 0, false, 0, 6),
('Falla en Sistema de Alarma', 'NO', 0, false, 0, 6),
('Falla en Sensor de Temperatura', 'NC', 1000, false, 0, 1),
('Baja Presión en Sistema Hidráulico', 'NO', 1200, false, 0, 2),
('Corto en Circuito de Iluminación', 'NC', 800, false, 1, 3),
('Nivel de Combustible Bajo Crítico', 'NO', 2000, false, 0, 4),
('Obstrucción en Tubería de Sentina', 'NC', 1800, false, 0, 5),
('Puerta de Cabina Abierta', 'NO', 0, false, 0, 6),
('Sobrecalentamiento Caja', 'NC', 1500, false, 1, 2),
('Falla en Generador Auxiliar', 'NO', 2000, false, 0, 3),
('Nivel de Aceite Crítico', 'NC', 1000, false, 0, 4),
('Fuga de Agua en Tanque de Sentina', 'NO', 1500, false, 0, 5),
('Falla Sistema de Alarma Principal', 'NC', 0, false, 1, 6),
('Baja Presión en Caja Reductora', 'NO', 1000, false, 0, 2),
('Corto Circuito en Sistema de Control', 'NC', 500, false, 0, 3),
('Nivel de Agua Bajo en Tanque', 'NO', 1500, false, 0, 4),
('Obstrucción en Filtro de Sentina', 'NC', 1800, false, 0, 5),
('Puerta de Sala de Máquinas Abierta', 'NO', 0, false, 0, 6),
('Falla en Engranaje Secundario', 'NC', 2000, false, 0, 2),
('Sobrevoltaje Detectado', 'NO', 1000, false, 1, 3),
('Bajo Nivel de Combustible', 'NC', 2000, false, 0, 4),
('Fuga de Agua en Sistema de Sentina', 'NO', 1500, false, 0, 5),
('Falla en SistemaSecundario', 'NC', 0, false, 2, 6),
('Corto en Circuito de Potencia', 'NO', 500, false, 0, 3),
('Nivel de Agua Crítico en Sentina', 'NC', 2000, false, 0, 5),
('Puerta Principal Abierta', 'NO', 0, false, 1, 6),
('Alta T° en Caja Secundaria', 'NC', 1800, false, 0, 2),
('Falla en Batería Auxiliar', 'NO', 2000, false, 0, 3),
('Nivel de Aceite Bajo Auxiliar', 'NC', 1000, false, 0, 4),
('Obstrucción en Válvula de Sentina', 'NO', 1800, false, 0, 5),
('Falla en Sistema Contra Incendios', 'NC', 0, false, 0, 6),
('Corto en Sistema de Iluminación', 'NO', 800, false, 4, 3),
('Nivel Agua en Tanque de Sentina', 'NC', 2000, false, 0, 5),
('Puerta de Acceso Abierta', 'NO', 0, false, 1, 6),
('Fallo en Sistema de Control', 'NO', 2000, false, 0, 3),
('Bajo Nivel Aceite Crítico', 'NC', 1000, false, 0, 4),
('Fuga de Combustible Grave', 'NO', 0, false, 0, 1),
('Falla Bomba Principal', 'NC', 2000, false, 0, 5),
('Sistema de Alarma Crítico', 'NO', 0, false, 0, 6);

SELECT * FROM alarmas;